// <auto-generated />
namespace CeeLearnAndDo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_props_to_user_registerModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_props_to_user_registerModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201803261352037_added_props_to_user_registerModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
